plugins {
    id 'java-library'
}

sourceCompatibility = 17.0
targetCompatibility = 17.0
compileTestJava.options.encoding = 'UTF-8'

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
   // flatDir { dirs 'libs' }
}

dependencies {
	api project('toti-libs:toti-common')
	api project('toti-libs:toti-database')
	api project('toti-libs:toti-files')
	api project('toti-libs:toti-db-testing')
	api project('toti-libs:toti-translate')
	api project('toti-libs:toti-http')
	api project('toti-libs:toti-templating')
	
	api project('toti-application')
	
	api project('toti-extensions:te-database')
	api project('toti-extensions:te-validation')
	api project('toti-extensions:te-templating')
	api project('toti-extensions:te-translator')
	api project('toti-extensions:te-ui')
}

