plugins {
    id 'java-library'
    id 'maven-publish'
}

ext {
	projectGroup = 'toti'
	coreGroup = 'toti.TOTI'
    libraryGroup = 'toti.TOTI.lib'
	extensionGroup = 'toti.TOTI.extension'
    publishPath = '/home/coder/project/publish'
}
// ext.group = 'toti'
// ext.publishPath = '/home/coder/project/repository';

group = project.projectGroup
version = '1.0'

publishing {
    publications {
        myLibrary(MavenPublication) {
            from components.java
        }
    }

     repositories {
        maven {
            name = "local"
            url = uri(project.publishPath)
        }
    }
}

compileTestJava.options.encoding = 'UTF-8'

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
   // flatDir { dirs 'libs' }
}

dependencies {
	api project('toti-libs:toti-common')
	api project('toti-libs:toti-database')
	api project('toti-libs:toti-files')
	api project('toti-libs:toti-translate')
	api project('toti-libs:toti-tcpip')
	api project('toti-libs:toti-templating')
	
	api project('toti-core')
	
	api project('toti-extensions:te-database')
	api project('toti-extensions:te-validation')
	api project('toti-extensions:te-templating')
	api project('toti-extensions:te-translator')
	api project('toti-extensions:te-ui')
}

