
rootProject.name = 'TOTI'


include('toti-libs:toti-common')
include('toti-libs:toti-database')
include('toti-libs:toti-files')
include('toti-libs:toti-translate')

include('toti-libs:toti-templating')
include('toti-libs:toti-tcpip')

include('toti-core')

include('toti-extensions:te-ui')
//include('toti-extensions:te-validator')
include('toti-extensions:te-database')
include('toti-extensions:te-templating')
include('toti-extensions:te-translator')
include('toti-extensions:te-validation')

include('examples:get-started')
include('examples:demo')