
// Apply the java-library plugin to add support for Java Library
plugins {
    id 'java-library'
	id 'java-test-fixtures'
}

compileTestJava.options.encoding = 'UTF-8'
// In this section you declare where to find the dependencies of your project
repositories {
    mavenCentral()
}

dependencies {
	testImplementation(testFixtures(project))

	// https://mvnrepository.com/artifact/org.slf4j/slf4j-api
	//api group: 'org.slf4j', name: 'slf4j-api', version: '2.0.0-alpha7'
	// https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
	api group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.23.1'
	
	// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
	api group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
	

	// https://github.com/gradle/gradle/issues/34512
	testFixturesRuntimeOnly "org.junit.platform:junit-platform-launcher"
	// https://mvnrepository.com/artifact/org.mockito/mockito-core
	testFixturesImplementation group: 'org.mockito', name: 'mockito-core', version: '2.19.1'
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
	testFixturesImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.11.2'
	testFixturesRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.2'
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params
	testFixturesImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.11.2'

	testImplementation files('tests/filesList.jar')
}

