http.port=83
http.secured-port=446
http.thread-pool=100
# 90 s
http.read-timeout=90000
# 20kB
http.max-request-size=20480
http.charset=UTF-8

http.key-store.path=certificates/cert.p12
http.key-store.password=betasecret
http.key-store.type=PKCS12
http.key-store.checkSNI=false

# http.trust-store=
# http.trust-store-password=
# http.trust-store-type=

applications.demo.resource-path=www
applications.demo.dir-allowed=true
applications.demo.dir-default-file=index.html
applications.demo.logs-path=logs
applications.demo.headers.1=Access-Control-Allow-Origin:*
applications.demo.headers.2=Server:TOTI
applications.demo.headers.3=Server:Properties set
applications.demo.autostart=true

applications.demo.templating.temp=temp/examples
applications.demo.templating.delete-temp-java=true
applications.demo.templating.minimalize-templates=false

applications.demo.database.type
applications.demo.database.url
applications.demo.database.schema-name
applications.demo.database.login
applications.demo.database.password
applications.demo.database.pool-size

applications.demo.lang.locales=en,cs
applications.demo.lang.default=en
applications.demo.lang.locale.en.ltr=true
applications.demo.lang.locale.en.substitutions=en_GB