package toti.templating.parsing2.enums;

public enum JavaState {
	NOTHING, CANDIDATE1, JAVA, CANDIDATE_COMMENT, CODE, COMMENT,
	CLOSE_COMMENT_CANDIDATE1, CLOSE_COMMENT_CANDIDATE2, CLOSE_CANDIDATE
}
