http.port=82
http.secured-port=445
http.thread-pool=100
# 90 s
http.read-timeout=90000
# 20kB
http.max-request-size=20480
http.charset=UTF-8

http.key-store=certificates/cert.p12
http.key-store-password=betasecret
http.key-store-type=PKCS12

# http.trust-store=
# http.trust-store-password=
# http.trust-store-type=

applications.examples.resource-path=www
applications.examples.dir-allowed=true
applications.examples.dir-default-file=index.html
applications.examples.dev-addresses.1=127.0.0.1
applications.examples.dev-addresses.2=0:0:0:0:0:0:0:1
applications.examples.logs-path=logs
applications.examples.headers.1=Access-Control-Allow-Origin:*
applications.examples.autostart=true

applications.examples.templating.temp=temp/examples
applications.examples.templating.delete-temp-java=true
applications.examples.templating.minimalize-templates=false

applications.examples.database.type
applications.examples.database.url
applications.examples.database.schema-name
applications.examples.database.login
applications.examples.database.password
applications.examples.database.pool-size

applications.examples.lang.locales=en,cs
applications.examples.lang.default=en
applications.examples.lang.locale.en.ltr=true
applications.examples.lang.locale.en.substitutions=en_GB