plugins {
	id 'java-library'
	id 'java-test-fixtures'
}

sourceCompatibility = 17.0
targetCompatibility = 17.0
compileTestJava.options.encoding = 'UTF-8'

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
}

dependencies {
	api project(':toti-libs:toti-common')
	api project(':toti-libs:toti-files')
	testImplementation(testFixtures(project))
	
	// compile files("${System.properties['java.home']}/../lib/tools.jar")
	// https://mvnrepository.com/artifact/junit/junit
	testImplementation  group: 'junit', name: 'junit', version: '4.12'
	// https://mvnrepository.com/artifact/org.mockito/mockito-core
	testImplementation  group: 'org.mockito', name: 'mockito-core', version: '2.19.1'	
	// https://mvnrepository.com/artifact/pl.pragmatists/JUnitParams
	testImplementation  group: 'pl.pragmatists', name: 'JUnitParams', version: '1.1.1'
	
	testImplementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
}

