
// Apply the java-library plugin to add support for Java Library
plugins {
    id 'java-library'
}

compileTestJava.options.encoding = 'UTF-8'
// In this section you declare where to find the dependencies of your project
repositories {
    mavenCentral()
}

dependencies {
	api project(':toti-libs:toti-common')
	api project(':toti-libs:toti-files')
	
	// https://github.com/gradle/gradle/issues/34512
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
	// https://mvnrepository.com/artifact/org.mockito/mockito-core
	testImplementation group: 'org.mockito', name: 'mockito-core', version: '2.19.1'
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.11.2'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.2'
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.11.2'

}

