plugins {
    id 'java-library'
}

sourceCompatibility = 17.0
targetCompatibility = 17.0
compileTestJava.options.encoding = 'UTF-8'

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
}

dependencies {
	api project(':toti-libs:toti-common')
	api project(':toti-libs:toti-http')
	testImplementation(testFixtures(project(":toti-libs:toti-db-testing")))
	
	//implementation group: 'at.favre.lib', name: 'bcrypt', version: '0.9.0'
	
	// used for Link:create
    implementation group:'org.objenesis',name:'objenesis',version:'2.4'
    implementation group:'net.bytebuddy',name:'byte-buddy',version:'1.8.13'
    implementation group:'net.bytebuddy',name:'byte-buddy-agent',version:'1.8.1'
    
    // https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server
	implementation group: 'org.eclipse.jetty', name: 'jetty-server', version: '12.0.10'
	// https://mvnrepository.com/artifact/org.eclipse.jetty.http2/jetty-http2-server
	implementation group: 'org.eclipse.jetty.http2', name: 'jetty-http2-server', version: '12.0.10'
	// https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-alpn-server
	implementation group: 'org.eclipse.jetty', name: 'jetty-alpn-server', version: '12.0.11'
	// https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-alpn-java-server
	implementation group: 'org.eclipse.jetty', name: 'jetty-alpn-java-server', version: '12.0.11'
	// https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/jetty-websocket-jetty-api
	implementation group: 'org.eclipse.jetty.websocket', name: 'jetty-websocket-jetty-api', version: '12.0.11'
	// https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/jetty-websocket-jetty-server
	implementation group: 'org.eclipse.jetty.websocket', name: 'jetty-websocket-jetty-server', version: '12.0.11'

	// https://mvnrepository.com/artifact/org.postgresql/postgresql
	//testImplementation  group: 'org.postgresql', name: 'postgresql', version: '42.2.16'

	// https://mvnrepository.com/artifact/mysql/mysql-connector-java
	//testImplementation  group: 'mysql', name: 'mysql-connector-java', version: '8.0.17'
	
	//testCompile fileTree(dir: "libs/derby", includes: ['*.jar'])
	
	// https://mvnrepository.com/artifact/junit/junit
	testImplementation  group: 'junit', name: 'junit', version: '4.12'
	// https://mvnrepository.com/artifact/org.mockito/mockito-core
	testImplementation  group: 'org.mockito', name: 'mockito-core', version: '2.19.1'	
	// https://mvnrepository.com/artifact/pl.pragmatists/JUnitParams
	// testImplementation group: 'pl.pragmatists', name: 'JUnitParams', version: '1.1.1'
	testImplementation 'com.github.Pragmatists:JUnitParams:b8647f177a'
	
	testImplementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
}

