
// Apply the java-library plugin to add support for Java Library
plugins {
    id 'java-library'
	id 'java-test-fixtures'
}

compileTestJava.options.encoding = 'UTF-8'
// In this section you declare where to find the dependencies of your project
repositories {
    mavenCentral()
    flatDir { dirs 'libs' }
}

dependencies {
	api project(':toti-libs:toti-common')
	api project(':toti-libs:toti-files')
	testImplementation(testFixtures(project))
	
	// https://github.com/gradle/gradle/issues/34512
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
	testFixturesRuntimeOnly "org.junit.platform:junit-platform-launcher"
	// https://mvnrepository.com/artifact/org.mockito/mockito-core
	testImplementation group: 'org.mockito', name: 'mockito-core', version: '2.19.1'
	testFixturesImplementation group: 'org.mockito', name: 'mockito-core', version: '2.19.1'
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.11.2'
	testFixturesImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.11.2'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.2'
	testFixturesRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.2'
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.11.2'
	testFixturesImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.11.2'

	
	// https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
	testImplementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.47.0.0'
	// https://mvnrepository.com/artifact/mysql/mysql-connector-java
	testImplementation group: 'mysql', name: 'mysql-connector-java', version: '8.0.17'
	
	testImplementation fileTree(dir: "libs/derby", includes: ['*.jar'])
	// https://mvnrepository.com/artifact/org.postgresql/postgresql
	testImplementation group: 'org.postgresql', name: 'postgresql', version: '42.2.16'

	// https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
	//testCompile group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '9.1.1.jre15-preview'

	// https://mvnrepository.com/artifact/com.microsoft.sqlserver/sqljdbc4
	testImplementation group: 'com.microsoft.sqlserver', name: 'sqljdbc41', version: '4.1'


}

