
// Apply the java-library plugin to add support for Java Library
plugins {
    id 'java-library'
}

sourceCompatibility = 17.0
targetCompatibility = 17.0
compileTestJava.options.encoding = 'UTF-8'
// In this section you declare where to find the dependencies of your project
repositories {
    mavenCentral()
}

dependencies {
	api project(':toti-libs:toti-common')
	api project(':toti-libs:toti-files')
	
	// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
	implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
	// https://mvnrepository.com/artifact/commons-codec/commons-codec
	implementation group: 'commons-codec', name: 'commons-codec', version: '1.15'
    
    // https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server
	implementation group: 'org.eclipse.jetty', name: 'jetty-server', version: '12.0.10'
	// https://mvnrepository.com/artifact/org.eclipse.jetty.http2/jetty-http2-server
	implementation group: 'org.eclipse.jetty.http2', name: 'jetty-http2-server', version: '12.0.10'
	// https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-alpn-server
	implementation group: 'org.eclipse.jetty', name: 'jetty-alpn-server', version: '12.0.11'
	// https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-alpn-java-server
	implementation group: 'org.eclipse.jetty', name: 'jetty-alpn-java-server', version: '12.0.11'
	// https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/jetty-websocket-jetty-api
	implementation group: 'org.eclipse.jetty.websocket', name: 'jetty-websocket-jetty-api', version: '12.0.11'
	// https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/jetty-websocket-jetty-server
	implementation group: 'org.eclipse.jetty.websocket', name: 'jetty-websocket-jetty-server', version: '12.0.11'

	// https://mvnrepository.com/artifact/junit/junit
	testImplementation group: 'junit', name: 'junit', version: '4.12'
	
	// https://mvnrepository.com/artifact/org.mockito/mockito-core
	testImplementation group: 'org.mockito', name: 'mockito-core', version: '2.19.1'
	
	// https://mvnrepository.com/artifact/pl.pragmatists/JUnitParams
	testImplementation group: 'pl.pragmatists', name: 'JUnitParams', version: '1.1.1'

}

